# Generated by Django 2.0.3 on 2018-05-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmarticle',
            name='Tag',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
