# Generated by Django 2.0.3 on 2018-05-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0002_algorithmarticle_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmarticle',
            name='id',
        ),
        migrations.AlterField(
            model_name='algorithmarticle',
            name='Title',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
