# Generated by Django 2.0.3 on 2018-05-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0003_auto_20180529_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmarticle',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='algorithmarticle',
            name='Title',
            field=models.CharField(max_length=40, primary_key=True),
        ),
    ]
