# Generated by Django 2.0.3 on 2018-05-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0008_auto_20180529_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmarticle',
            name='Id',
        ),
    ]
