# Generated by Django 2.0.3 on 2018-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiDu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=60)),
                ('Link', models.CharField(max_length=300)),
                ('SearchHeat', models.IntegerField()),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DouBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filmname', models.CharField(max_length=60)),
                ('Link', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageStructrue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pagename', models.CharField(max_length=40)),
                ('Link', models.CharField(max_length=400)),
                ('Img', models.CharField(max_length=400)),
                ('Content', models.CharField(max_length=200)),
                ('Trycount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=24)),
                ('Target', models.CharField(max_length=20)),
                ('Issucceed', models.BooleanField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDUWH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.DecimalField(decimal_places=0, max_digits=12)),
                ('Password', models.CharField(max_length=16)),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StackOverflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopQuestion', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=300)),
                ('Answers', models.IntegerField()),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TengXun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=60)),
                ('Link', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XinLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=60)),
                ('Link', models.CharField(max_length=300)),
                ('SearchHeat', models.IntegerField()),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZhiHu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=60)),
                ('Link', models.CharField(max_length=300)),
                ('Answers', models.IntegerField()),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZhiWang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Author', models.CharField(max_length=20)),
                ('Insititute', models.CharField(max_length=20)),
                ('Journal', models.CharField(max_length=20)),
                ('Keyword', models.CharField(max_length=20)),
                ('Content', models.TextField()),
                ('ScrapyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zhiwang',
            unique_together={('Title', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='zhihu',
            unique_together={('Item', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='xinlang',
            unique_together={('Keyword', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='tengxun',
            unique_together={('Item', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='stackoverflow',
            unique_together={('TopQuestion', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='sduwh',
            unique_together={('StudentID', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('Username', 'Date')},
        ),
        migrations.AlterUniqueTogether(
            name='github',
            unique_together={('Item', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='douban',
            unique_together={('Filmname', 'ScrapyDate')},
        ),
        migrations.AlterUniqueTogether(
            name='baidu',
            unique_together={('Keyword', 'ScrapyDate')},
        ),
    ]
