# Generated by Django 2.0.3 on 2018-03-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_site', '0002_auto_20180329_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SDUWH',
            new_name='SDU',
        ),
    ]
