# Generated by Django 2.0.3 on 2018-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_site', '0005_auto_20180426_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentfault',
            name='AuthorLink',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
