# Generated by Django 2.0.3 on 2018-04-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_site', '0008_auto_20180426_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentfault',
            name='Item',
            field=models.CharField(max_length=60),
        ),
    ]
