# Generated by Django 2.0.3 on 2018-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_site', '0010_auto_20180426_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='segmentfaultfull',
            fields=[
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('title_url', models.URLField()),
                ('createdDate', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('author_link', models.CharField(max_length=100)),
            ],
        ),
    ]
