# Generated by Django 2.0.3 on 2018-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Username', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=16)),
                ('Email', models.EmailField(max_length=36)),
            ],
        ),
    ]
